### ISSUE TITLE
Reopening a tip with FrameratePatch 0.3.1 crashes Opus Magnum

### ISSUE THREAD

**Issue by ItsKazyan** [icwass/FrameratePatch#1]
![Screenshot from 2024-01-14 17-24-37](https://github.com/icwass/FrameratePatch/assets/50607817/966b26c6-fe7a-4ff1-bc7e-9ca783904cf2)

Pressing this button normally reopens shows a puzzle's tip. With FrameratePatch 0.3.1 installed (and no other mods besides Quintessential), this button instead crashes the game.

Only _reopening_ a tip causes this behavior, interestingly. With a save.dat file where a puzzle's tip has not been seen yet, i.e. it can be seen immediately upon loading the puzzle, the tip behaves normally. This occurs whether the tip's image is a recording of a solution or a static image; e.g. this crash is still observed with the Golden Thread Recycling level in Reductive Metallurgy Campaign.

**Comment by icwass** [comment]
Should be fixed in v0.3.2. Thanks for finding this issue and reporting it!
